### ISSUE TITLE
Endless Listview to Json very long

### ISSUE THREAD

**Issue by TuxRneR** [hishamMuneer/JsonParsingDemo#3]
Hello, its a great this tutorial and code example, but. Can you helpme to implement Endless on bottom scroll list, to load more items in the Listview of movies if my Json file contan more of 50 movies?
Thanks!

**Comment by hishamMuneer** [comment]
```
private int preLast;
--> listQuestions.setOnScrollListener(this); // this goes inside oncreate or something


@Override
public void onScrollStateChanged(AbsListView absListView, int i) {
    // not used
}

@Override
public void onScroll(AbsListView lw, final int firstVisibleItem,
final int visibleItemCount, final int totalItemCount) {

    switch(lw.getId()) {
        case R.id.listQuestions:

            // Make your calculation stuff here. You have all your
            // needed info from the parameters of this function.

            // Sample calculation to determine if the last
            // item is fully visible.
            final int lastItem = firstVisibleItem + visibleItemCount;
            if(lastItem == totalItemCount) {
                if(preLast!=lastItem){ //to avoid multiple calls for last item
                    Log.d("Last", "Last");
                    preLast = lastItem;

                    // Call your code here, Congrats you have reached the bottom of the list.
                }
            }
    }
}
```

**Comment by TuxRneR** [comment]
Work but this is not to i need. look  when the application run, the list of more 50 movies appear, i want to  see the first 10 movies, and when the scroll top to bottom, load the others 10 movies. Please implement in this tuto, because in this demo you use the Adapter to add and the listview, and i have problems with this. PLEASE

**Comment by JoaquinMontesinos** [comment]
@HackJoues  Have you got it?  (... the scroll to bottom, load the others 10 movies ...)

@hishamMuneer  Congratulation for your tutorial! It's realy good. Did you have extended other functionalities in this example? (Like slider in the photo of DetailActivity.java or  Animation in the transition)  

It would really be useful any extension!!
